// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserCloseTabInput
 */

/**
 * Close the current tab
 *
 * @param {BrowserCloseTabInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserCloseTab(input) {
  return callMCPTool("browser_close_tab", input);
}
