// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserCloseInput
 */

/**
 * Close the browser when the task is done and the browser is not needed anymore
 *
 * @param {BrowserCloseInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserClose(input) {
  return callMCPTool("browser_close", input);
}
