// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserEvaluateInput
 * @property {string} script JavaScript code to execute, () => { /* code */ }
 */

/**
 * Execute JavaScript in the browser console
 *
 * @param {BrowserEvaluateInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserEvaluate(input) {
  return callMCPTool("browser_evaluate", input);
}
