// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserFormInputFillInput
 * @property {string} [selector] CSS selector for input field, priority use index, if index is not provided, use selector
 * @property {number} [index] Index of the element to fill
 * @property {string} value Value to fill
 * @property {boolean} [clear] Whether to clear existing text before filling
 */

/**
 * Fill out an input field, before using the tool, Either 'index' or 'selector' must be provided
 *
 * @param {BrowserFormInputFillInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserFormInputFill(input) {
  return callMCPTool("browser_form_input_fill", input);
}
