// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGetTextInput
 */

/**
 * Get the text content of the current page
 *
 * @param {BrowserGetTextInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGetText(input) {
  return callMCPTool("browser_get_text", input);
}
