// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGetDownloadListInput
 */

/**
 * Get the list of downloaded files
 *
 * @param {BrowserGetDownloadListInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGetDownloadList(input) {
  return callMCPTool("browser_get_download_list", input);
}
