// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGetMarkdownInput
 */

/**
 * Get the markdown content of the current page
 *
 * @param {BrowserGetMarkdownInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGetMarkdown(input) {
  return callMCPTool("browser_get_markdown", input);
}
