// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGetClickableElementsInput
 */

/**
 * Get the clickable or hoverable or selectable elements on the current page, don't call this tool multiple times
 *
 * @param {BrowserGetClickableElementsInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGetClickableElements(input) {
  return callMCPTool("browser_get_clickable_elements", input);
}
