// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGoBackInput
 */

/**
 * Go back to the previous page
 *
 * @param {BrowserGoBackInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGoBack(input) {
  return callMCPTool("browser_go_back", input);
}
