// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserGoForwardInput
 */

/**
 * Go forward to the next page
 *
 * @param {BrowserGoForwardInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserGoForward(input) {
  return callMCPTool("browser_go_forward", input);
}
