// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserHoverInput
 * @property {number} [index] Index of the element to hover
 * @property {string} [selector] CSS selector for element to hover
 */

/**
 * Hover an element on the page, Either 'index' or 'selector' must be provided
 *
 * @param {BrowserHoverInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserHover(input) {
  return callMCPTool("browser_hover", input);
}
