// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserNavigateInput
 * @property {string} url
 */

/**
 * Navigate to a URL
 *
 * @param {BrowserNavigateInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserNavigate(input) {
  return callMCPTool("browser_navigate", input);
}
