// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserNewTabInput
 * @property {string} url URL to open in the new tab
 */

/**
 * Open a new tab
 *
 * @param {BrowserNewTabInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserNewTab(input) {
  return callMCPTool("browser_new_tab", input);
}
