// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserPressKeyInput
 * @property {"Enter"|"Tab"|"Escape"|"Backspace"|"Delete"|"Insert"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"ArrowLeft"|"ArrowRight"|"ArrowUp"|"ArrowDown"|"PageUp"|"PageDown"|"Home"|"End"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"MetaLeft"|"MetaRight"|"CapsLock"|"PrintScreen"|"ScrollLock"|"Pause"|"ContextMenu"} key Name of the key to press or a character to generate, such as Enter, Tab, Escape, Backspace, Delete, Insert, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, ArrowLeft, ArrowRight, ArrowUp, ArrowDown, PageUp, PageDown, Home, End, ShiftLeft, ShiftRight, ControlLeft, ControlRight, AltLeft, AltRight, MetaLeft, MetaRight, CapsLock, PrintScreen, ScrollLock, Pause, ContextMenu
 */

/**
 * Press a key on the keyboard
 *
 * @param {BrowserPressKeyInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserPressKey(input) {
  return callMCPTool("browser_press_key", input);
}
