// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserReadLinksInput
 */

/**
 * Get all links on the current page
 *
 * @param {BrowserReadLinksInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserReadLinks(input) {
  return callMCPTool("browser_read_links", input);
}
