// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserScreenshotInput
 * @property {string} [name] Name for the screenshot
 * @property {string} [selector] CSS selector for element to screenshot
 * @property {number} [index] index of the element to screenshot
 * @property {number} [width] Width in pixels (default: viewport width)
 * @property {number} [height] Height in pixels (default: viewport height)
 * @property {boolean} [fullPage] Full page screenshot (default: false)
 * @property {boolean} [highlight] Highlight the element
 */

/**
 * Take a screenshot of the current page or a specific element
 *
 * @param {BrowserScreenshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserScreenshot(input) {
  return callMCPTool("browser_screenshot", input);
}
