// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserScrollInput
 * @property {number} [amount] Pixels to scroll (positive for down, negative for up), if the amount is not provided, scroll to the bottom of the page
 */

/**
 * Scroll the page
 *
 * @param {BrowserScrollInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserScroll(input) {
  return callMCPTool("browser_scroll", input);
}
