// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserSelectInput
 * @property {number} [index] Index of the element to select
 * @property {string} [selector] CSS selector for element to select
 * @property {string} value Value to select
 */

/**
 * Select an element on the page with index, Either 'index' or 'selector' must be provided
 *
 * @param {BrowserSelectInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserSelect(input) {
  return callMCPTool("browser_select", input);
}
