// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserSwitchTabInput
 * @property {number} index Tab index to switch to
 */

/**
 * Switch to a specific tab
 *
 * @param {BrowserSwitchTabInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserSwitchTab(input) {
  return callMCPTool("browser_switch_tab", input);
}
