// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserTabListInput
 */

/**
 * Get the list of tabs
 *
 * @param {BrowserTabListInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserTabList(input) {
  return callMCPTool("browser_tab_list", input);
}
