// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserVisionScreenCaptureInput
 */

/**
 * Take a screenshot of the current page for vision mode
 *
 * @param {BrowserVisionScreenCaptureInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserVisionScreenCapture(input) {
  return callMCPTool("browser_vision_screen_capture", input);
}
