// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsClickInput
 * @property {string} uid The uid of an element on the page from the page content snapshot
 * @property {boolean} [dblClick] Set to true for double clicks. Default is false.
 */

/**
 * Clicks on the provided element
 *
 * @param {ChromeDevtoolsClickInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsClick(input) {
  return callMCPTool("chrome_devtools_click", input);
}
