// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsClosePageInput
 * @property {number} pageIdx The index of the page to close. Call list_pages to list pages.
 */

/**
 * Closes the page by its index. The last open page cannot be closed.
 *
 * @param {ChromeDevtoolsClosePageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsClosePage(input) {
  return callMCPTool("chrome_devtools_close_page", input);
}
