// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsDragInput
 * @property {string} from_uid The uid of the element to drag
 * @property {string} to_uid The uid of the element to drop into
 */

/**
 * Drag an element onto another element
 *
 * @param {ChromeDevtoolsDragInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsDrag(input) {
  return callMCPTool("chrome_devtools_drag", input);
}
