// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsEmulateCpuInput
 * @property {number} throttlingRate The CPU throttling rate representing the slowdown factor 1-20x. Set the rate to 1 to disable throttling
 */

/**
 * Emulates CPU throttling by slowing down the selected page's execution.
 *
 * @param {ChromeDevtoolsEmulateCpuInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsEmulateCpu(input) {
  return callMCPTool("chrome_devtools_emulate_cpu", input);
}
