// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsEmulateNetworkInput
 * @property {"No emulation"|"Offline"|"Slow 3G"|"Fast 3G"|"Slow 4G"|"Fast 4G"} throttlingOption The network throttling option to emulate. Available throttling options are: No emulation, Offline, Slow 3G, Fast 3G, Slow 4G, Fast 4G. Set to "No emulation" to disable. Set to "Offline" to simulate offline network conditions.
 */

/**
 * Emulates network conditions such as throttling or offline mode on the selected page.
 *
 * @param {ChromeDevtoolsEmulateNetworkInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsEmulateNetwork(input) {
  return callMCPTool("chrome_devtools_emulate_network", input);
}
