// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsFillInput
 * @property {string} uid The uid of an element on the page from the page content snapshot
 * @property {string} value The value to fill in
 */

/**
 * Type text into a input, text area or select an option from a <select> element.
 *
 * @param {ChromeDevtoolsFillInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsFill(input) {
  return callMCPTool("chrome_devtools_fill", input);
}
