// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsFillFormInput
 * @property {object[]} elements Elements from snapshot to fill out.
 */

/**
 * Fill out multiple form elements at once
 *
 * @param {ChromeDevtoolsFillFormInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsFillForm(input) {
  return callMCPTool("chrome_devtools_fill_form", input);
}
