// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsGetConsoleMessageInput
 * @property {number} msgid The msgid of a console message on the page from the listed console messages
 */

/**
 * Gets a console message by its ID. You can get all messages by calling list_console_messages.
 *
 * @param {ChromeDevtoolsGetConsoleMessageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsGetConsoleMessage(input) {
  return callMCPTool("chrome_devtools_get_console_message", input);
}
