// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsGetNetworkRequestInput
 * @property {number} reqid The reqid of a request on the page from the listed network requests
 */

/**
 * Gets a network request by URL. You can get all requests by calling list_network_requests.
 *
 * @param {ChromeDevtoolsGetNetworkRequestInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsGetNetworkRequest(input) {
  return callMCPTool("chrome_devtools_get_network_request", input);
}
