// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsHandleDialogInput
 * @property {"accept"|"dismiss"} action Whether to dismiss or accept the dialog
 * @property {string} [promptText] Optional prompt text to enter into the dialog.
 */

/**
 * If a browser dialog was opened, use this command to handle it
 *
 * @param {ChromeDevtoolsHandleDialogInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsHandleDialog(input) {
  return callMCPTool("chrome_devtools_handle_dialog", input);
}
