// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsHoverInput
 * @property {string} uid The uid of an element on the page from the page content snapshot
 */

/**
 * Hover over the provided element
 *
 * @param {ChromeDevtoolsHoverInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsHover(input) {
  return callMCPTool("chrome_devtools_hover", input);
}
