// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsListConsoleMessagesInput
 * @property {number} [pageSize] Maximum number of messages to return. When omitted, returns all requests.
 * @property {number} [pageIdx] Page number to return (0-based). When omitted, returns the first page.
 * @property {"log"|"debug"|"info"|"error"|"warn"|"dir"|"dirxml"|"table"|"trace"|"clear"|"startGroup"|"startGroupCollapsed"|"endGroup"|"assert"|"profile"|"profileEnd"|"count"|"timeEnd"|"verbose"[]} [types] Filter messages to only return messages of the specified resource types. When omitted or empty, returns all messages.
 * @property {boolean} [includePreservedMessages] Set to true to return the preserved messages over the last 3 navigations.
 */

/**
 * List all console messages for the currently selected page since the last navigation.
 *
 * @param {ChromeDevtoolsListConsoleMessagesInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsListConsoleMessages(input) {
  return callMCPTool("chrome_devtools_list_console_messages", input);
}
