// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsListPagesInput
 */

/**
 * Get a list of pages open in the browser.
 *
 * @param {ChromeDevtoolsListPagesInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsListPages(input) {
  return callMCPTool("chrome_devtools_list_pages", input);
}
