// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsListNetworkRequestsInput
 * @property {number} [pageSize] Maximum number of requests to return. When omitted, returns all requests.
 * @property {number} [pageIdx] Page number to return (0-based). When omitted, returns the first page.
 * @property {("document"|"stylesheet"|"image"|"media"|"font"|"script"|"texttrack"|"xhr"|"fetch"|"prefetch"|"eventsource"|"websocket"|"manifest"|"signedexchange"|"ping"|"cspviolationreport"|"preflight"|"fedcm"|"other")[]} [resourceTypes] Filter requests to only return requests of the specified resource types. When omitted or empty, returns all requests.
 * @property {boolean} [includePreservedRequests] Set to true to return the preserved requests over the last 3 navigations.
 */

/**
 * List all requests for the currently selected page since the last navigation.
 *
 * @param {ChromeDevtoolsListNetworkRequestsInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsListNetworkRequests(input) {
  return callMCPTool("chrome_devtools_list_network_requests", input);
}
