// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsNavigatePageInput
 * @property {string} url URL to navigate the page to
 * @property {number} [timeout] Maximum wait time in milliseconds. If set to 0, the default timeout will be used.
 */

/**
 * Navigates the currently selected page to a URL.
 *
 * @param {ChromeDevtoolsNavigatePageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsNavigatePage(input) {
  return callMCPTool("chrome_devtools_navigate_page", input);
}
