// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsNavigatePageHistoryInput
 * @property {"back"|"forward"} navigate Whether to navigate back or navigate forward in the selected pages history
 * @property {number} [timeout] Maximum wait time in milliseconds. If set to 0, the default timeout will be used.
 */

/**
 * Navigates the currently selected page.
 *
 * @param {ChromeDevtoolsNavigatePageHistoryInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsNavigatePageHistory(input) {
  return callMCPTool("chrome_devtools_navigate_page_history", input);
}
