// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsNewPageInput
 * @property {string} url URL to load in a new page.
 * @property {number} [timeout] Maximum wait time in milliseconds. If set to 0, the default timeout will be used.
 */

/**
 * Creates a new page
 *
 * @param {ChromeDevtoolsNewPageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsNewPage(input) {
  return callMCPTool("chrome_devtools_new_page", input);
}
