// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsPerformanceStopTraceInput
 */

/**
 * Stops the active performance trace recording on the selected page.
 *
 * @param {ChromeDevtoolsPerformanceStopTraceInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsPerformanceStopTrace(input) {
  return callMCPTool("chrome_devtools_performance_stop_trace", input);
}
