// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsPerformanceAnalyzeInsightInput
 * @property {string} insightName The name of the Insight you want more information on. For example: "DocumentLatency" or "LCPBreakdown"
 */

/**
 * Provides more detailed information on a specific Performance Insight that was highlighted in the results of a trace recording.
 *
 * @param {ChromeDevtoolsPerformanceAnalyzeInsightInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsPerformanceAnalyzeInsight(input) {
  return callMCPTool("chrome_devtools_performance_analyze_insight", input);
}
