// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsPerformanceStartTraceInput
 * @property {boolean} reload Determines if, once tracing has started, the page should be automatically reloaded.
 * @property {boolean} autoStop Determines if the trace recording should be automatically stopped.
 */

/**
 * Starts a performance trace recording on the selected page. This can be used to look for performance problems and insights to improve the performance of the page. It will also report Core Web Vital (CWV) scores for the page.
 *
 * @param {ChromeDevtoolsPerformanceStartTraceInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsPerformanceStartTrace(input) {
  return callMCPTool("chrome_devtools_performance_start_trace", input);
}
