// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsResizePageInput
 * @property {number} width Page width
 * @property {number} height Page height
 */

/**
 * Resizes the selected page's window so that the page has specified dimension
 *
 * @param {ChromeDevtoolsResizePageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsResizePage(input) {
  return callMCPTool("chrome_devtools_resize_page", input);
}
