// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsSelectPageInput
 * @property {number} pageIdx The index of the page to select. Call list_pages to list pages.
 */

/**
 * Select a page as a context for future tool calls.
 *
 * @param {ChromeDevtoolsSelectPageInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsSelectPage(input) {
  return callMCPTool("chrome_devtools_select_page", input);
}
