// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsTakeScreenshotInput
 * @property {"png"|"jpeg"|"webp"} [format] Type of format to save the screenshot as. Default is "png"
 * @property {number} [quality] Compression quality for JPEG and WebP formats (0-100). Higher values mean better quality but larger file sizes. Ignored for PNG format.
 * @property {string} [uid] The uid of an element on the page from the page content snapshot. If omitted takes a pages screenshot.
 * @property {boolean} [fullPage] If set to true takes a screenshot of the full page instead of the currently visible viewport. Incompatible with uid.
 * @property {string} [filePath] The absolute path, or a path relative to the current working directory, to save the screenshot to instead of attaching it to the response.
 */

/**
 * Take a screenshot of the page or element.
 *
 * @param {ChromeDevtoolsTakeScreenshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsTakeScreenshot(input) {
  return callMCPTool("chrome_devtools_take_screenshot", input);
}
