// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsTakeSnapshotInput
 * @property {boolean} [verbose] Whether to include all possible information available in the full a11y tree. Default is false.
 */

/**
 * Take a text snapshot of the currently selected page based on the a11y tree. The snapshot lists page elements along with a unique
identifier (uid). Always use the latest snapshot. Prefer taking a snapshot over taking a screenshot.
 *
 * @param {ChromeDevtoolsTakeSnapshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsTakeSnapshot(input) {
  return callMCPTool("chrome_devtools_take_snapshot", input);
}
