// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsUploadFileInput
 * @property {string} uid The uid of the file input element or an element that will open file chooser on the page from the page content snapshot
 * @property {string} filePath The local path of the file to upload
 */

/**
 * Upload a file through a provided element.
 *
 * @param {ChromeDevtoolsUploadFileInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsUploadFile(input) {
  return callMCPTool("chrome_devtools_upload_file", input);
}
