// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsWaitForInput
 * @property {string} text Text to appear on the page
 * @property {number} [timeout] Maximum wait time in milliseconds. If set to 0, the default timeout will be used.
 */

/**
 * Wait for the specified text to appear on the selected page.
 *
 * @param {ChromeDevtoolsWaitForInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsWaitFor(input) {
  return callMCPTool("chrome_devtools_wait_for", input);
}
