// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxConvertToMarkdownInput
 * @property {string} path Absolute sandbox path to the source file.
 */

/**
 * Convert a PDF, HTML, or DOCX file to clean markdown.
 *
 * @param {SandboxConvertToMarkdownInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxConvertToMarkdown(input) {
  return callMCPTool("sandbox_convert_to_markdown", input);
}
