// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxExecuteCodeInput
 * @property {string} code Source code to execute.
 * @property {string} language Language identifier.
 */

/**
 * Execute Python or JavaScript code in the sandbox runtime.
 *
 * @param {SandboxExecuteCodeInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxExecuteCode(input) {
  return callMCPTool("sandbox_execute_code", input);
}
