// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxExecuteBashInput
 * @property {string} command Shell command to execute.
 * @property {number} [timeout] Seconds before forcing termination.
 */

/**
 * Run a shell command in the sandbox.
 *
 * @param {SandboxExecuteBashInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxExecuteBash(input) {
  return callMCPTool("sandbox_execute_bash", input);
}
