// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxGetContextInput
 */

/**
 * Return metadata about the running sandbox container.
 *
 * @param {SandboxGetContextInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxGetContext(input) {
  return callMCPTool("sandbox_get_context", input);
}
