// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserClickInput
 * @property {number} index 0-based element index.
 */

/**
 * Click an element by index from the last snapshot.
 *
 * @param {BrowserClickInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserClick(input) {
  return callMCPTool("browser_click", input);
}
