// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserFillInput
 * @property {number} index 0-based element index.
 * @property {string} value Text to type.
 */

/**
 * Type text into an input field identified by index.
 *
 * @param {BrowserFillInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserFill(input) {
  return callMCPTool("browser_fill", input);
}
