// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} BrowserTakeScreenshotInput
 * @property {"base64"|"binary"} [encoding] Output encoding.
 */

/**
 * Take a screenshot of the current page via the browser MCP server.
 *
 * @param {BrowserTakeScreenshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function browserTakeScreenshot(input) {
  return callMCPTool("browser_take_screenshot", input);
}
