// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxBrowserExecuteActionInput
 * @property {object} action
 */

/**
 * Execute a browser action on the current display.

Args:
    `action`: Dictionary containing `action_type` and relevant parameters.
            The `action_type` determines which parameters are required.

Action types and their parameters (auto-generated from models):
    - CLICK: {action_type: 'CLICK', x: Optional?, y: Optional?, button: Literal?, num_clicks: Literal?}
    - DOUBLE_CLICK: {action_type: 'DOUBLE_CLICK', x: Optional?, y: Optional?}
    - DRAG_REL: {action_type: 'DRAG_REL', x_offset: float, y_offset: float}
    - DRAG_TO: {action_type: 'DRAG_TO', x: float, y: float}
    - HOTKEY: {action_type: 'HOTKEY', keys: List}
    - KEY_DOWN: {action_type: 'KEY_DOWN', key: str}
    - KEY_UP: {action_type: 'KEY_UP', key: str}
    - MOUSE_DOWN: {action_type: 'MOUSE_DOWN', button: Literal?}
    - MOUSE_UP: {action_type: 'MOUSE_UP', button: Literal?}
    - MOVE_REL: {action_type: 'MOVE_REL', x_offset: float, y_offset: float}
    - MOVE_TO: {action_type: 'MOVE_TO', x: float, y: float}
    - PRESS: {action_type: 'PRESS', key: str}
    - RIGHT_CLICK: {action_type: 'RIGHT_CLICK', x: Optional?, y: Optional?}
    - SCROLL: {action_type: 'SCROLL', dx: int?, dy: int?}
    - TYPING: {action_type: 'TYPING', text: str, use_clipboard: Optional?}
    - WAIT: {action_type: 'WAIT', duration: float}

Returns:
    Dict containing `status` and `action_performed`

Raises:
    ValueError: If `action_type` is invalid or required parameters are missing
 *
 * @param {SandboxBrowserExecuteActionInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxBrowserExecuteAction(input) {
  return callMCPTool("sandbox_browser_execute_action", input);
}
