// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxBrowserScreenshotInput
 */

/**
 * Take a screenshot of the current display.

    Returns:
        Image: A screenshot of the current display in JPEG format with metadata.
 *
 * @param {SandboxBrowserScreenshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxBrowserScreenshot(input) {
  return callMCPTool("sandbox_browser_screenshot", input);
}
