// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxConvertToMarkdownInput
 * @property {string} uri
 */

/**
 * Convert a resource described by an http:, https:, file: or data: URI to markdown
 *
 * @param {SandboxConvertToMarkdownInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxConvertToMarkdown(input) {
  return callMCPTool("sandbox_convert_to_markdown", input);
}
