// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxExecuteCodeInput
 * @property {string} code
 * @property {unknown} [language]
 * @property {unknown} [timeout]
 */

/**
 * Execute code in Python or JavaScript runtime.

    Args:
        code: Code to execute
        language: Programming language ('python', 'javascript')
        timeout: Optional execution timeout in seconds

    Returns:
        Dict containing output, errors, and execution details
 *
 * @param {SandboxExecuteCodeInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxExecuteCode(input) {
  return callMCPTool("sandbox_execute_code", input);
}
