// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxExecuteBashInput
 * @property {string} cmd
 * @property {unknown} [cwd]
 * @property {boolean} [new_session]
 * @property {unknown} [timeout]
 */

/**
 * Execute a shell command. Sessions are managed automatically.

    Args:
        cmd: Shell command to execute
        cwd: Optional working directory (absolute path), default to '/tmp'
        new_session: If True, creates a new session instead of using the default
        timeout: Optional timeout in seconds for command execution (default: 30)

    Returns:
        Dict containing command, status, output, and exit_code
 *
 * @param {SandboxExecuteBashInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxExecuteBash(input) {
  return callMCPTool("sandbox_execute_bash", input);
}
