// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxFileOperationsInput
 * @property {string} action
 * @property {string} path
 * @property {unknown} [content]
 * @property {unknown} [target]
 * @property {unknown} [pattern]
 * @property {unknown} [encoding]
 * @property {unknown} [start_line]
 * @property {unknown} [end_line]
 * @property {boolean} [append]
 * @property {boolean} [recursive]
 * @property {boolean} [show_hidden]
 * @property {unknown} [file_types]
 * @property {boolean} [sudo]
 */

/**
 * Unified file system operations tool for agents. `/tmp` and `/home/$USER` are fully accessible.

    Args:
        action: Operation type - "read", "write", "replace", "search", "find", "list"
        path: File or directory path
        content: Content for write/replace operations (or regex for search)
        target: Target string for replace operations (new_str)
        pattern: Pattern for find operations (glob syntax)
        encoding: File encoding (utf-8, base64, raw)
        start_line: Starting line for read operations (0-based)
        end_line: Ending line for read operations (not included)
        append: Append mode for write operations
        recursive: Recursive mode for find/list operations
        show_hidden: Show hidden files in list operations
        file_types: Filter by file extensions for list operations
        sudo: Use sudo privileges

    Returns:
        Dict containing operation result and relevant data
 *
 * @param {SandboxFileOperationsInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxFileOperations(input) {
  return callMCPTool("sandbox_file_operations", input);
}
