// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxGetBrowserInfoInput
 */

/**
 * Get information about browser, like cdp url, viewport size, etc.

    Args:
        request (Dict): The incoming request context.
 *
 * @param {SandboxGetBrowserInfoInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxGetBrowserInfo(input) {
  return callMCPTool("sandbox_get_browser_info", input);
}
