// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxGetContextInput
 */

/**
 * Get sandbox environment information. aio system's version.

    Returns:
        Dict containing aio sandbox's environment info, version, and home directory
 *
 * @param {SandboxGetContextInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxGetContext(input) {
  return callMCPTool("sandbox_get_context", input);
}
