// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxGetPackagesInput
 * @property {"python"|"nodejs"} [language]
 */

/**
 * Get installed packages by language.

    Args:
        language: Optional language filter ('python' or 'nodejs')

    Returns: String listing installed packages
 *
 * @param {SandboxGetPackagesInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxGetPackages(input) {
  return callMCPTool("sandbox_get_packages", input);
}
