// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.
// Regenerate with: npm run generate:mcp-wrappers

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} SandboxStrReplaceEditorInput
 * @property {string} command
 * @property {string} path
 * @property {unknown} [file_text]
 * @property {unknown} [old_str]
 * @property {unknown} [new_str]
 * @property {unknown} [insert_line]
 * @property {unknown} [view_range]
 */

/**
 * Professional file editor tool using openhands_aci editor.

    This tool provides advanced file editing capabilities compatible with Anthropic's
    str_replace_editor interface. Parameters and behavior match the standard interface.

    Args:
        command: Command to execute ("view", "create", "str_replace", "insert", "undo_edit")
        path: File path to operate on
        file_text: File content for create command
        old_str: Original string to replace (for str_replace command)
        new_str: New string to replace with (for str_replace and insert commands)
        insert_line: Line number to insert at (for insert command)
        view_range: Line range for view command [start, end]

    Returns:
        Dict containing editor operation result
 *
 * @param {SandboxStrReplaceEditorInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function sandboxStrReplaceEditor(input) {
  return callMCPTool("sandbox_str_replace_editor", input);
}
