// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsListNetworkRequestsInput
 * @property {string} [filter] Substring filter on request URL.
 * @property {number} [limit] Maximum number of requests to return.
 */

/**
 * List all network requests captured since page load.
 *
 * @param {ChromeDevtoolsListNetworkRequestsInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsListNetworkRequests(input) {
  return callMCPTool("chrome_devtools_list_network_requests", input);
}
