// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsNavigateInput
 * @property {string} url Absolute URL to navigate to.
 * @property {"load"|"domcontentloaded"|"networkidle"} [wait_until] Page lifecycle event to wait for.
 */

/**
 * Navigate the active browser tab to a URL.
 *
 * @param {ChromeDevtoolsNavigateInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsNavigate(input) {
  return callMCPTool("chrome_devtools_navigate", input);
}
