// Generated by scripts/generate-mcp-wrappers.ts — do not edit by hand.

import { callMCPTool } from "../_client/callMCPTool.js";

/**
 * @typedef {object} ChromeDevtoolsTakeScreenshotInput
 * @property {boolean} [full_page] Capture beyond the viewport.
 * @property {number} [quality] JPEG quality 0-100.
 */

/**
 * Capture a full-page screenshot as base64 PNG.
 *
 * @param {ChromeDevtoolsTakeScreenshotInput} input
 * @returns {Promise<{ content: unknown[], structuredContent: unknown | null }>}
 */
export async function chromeDevtoolsTakeScreenshot(input) {
  return callMCPTool("chrome_devtools_take_screenshot", input);
}
